### PR TITLE
Fix denormalizing enums

### LINKED ISSUE #113: Enum support
Currently when using enums this lib serializer stores enum as `"field": {"name": "NAME", "#type": "App\\Enum\\MyEnum", "value": "name"}` and therefore fails to denormalize later for reading.
The problem was simpler - the denormalization part was only failing and therefore normalization is okay as is

### PR DESCRIPTION
**Pull request by norkunas**
Closes #113

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by norkunas** [comment]
Will this be merged? :)

**Comment by norkunas** [comment]
friendly ping @dunglas :)

File: src/Bundle/DependencyInjection/DunglasDoctrineJsonOdmExtension.php [hunk 1]
```diff
@@ -45,5 +46,9 @@ public function load(array $configs, ContainerBuilder $container): void
     {
         $loader = new XmlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
         $loader->load('services.xml');
+
+        if (!class_exists(BackedEnumNormalizer::class)) {
```
Comment (dunglas) [inline src/Bundle/DependencyInjection/DunglasDoctrineJsonOdmExtension.php:50]: You should also call `removeDefinition` if `\BackedEnum` doesn't exist because the class can exist even with old PHP versions (Symfony 5.4).

**Review by dunglas — CHANGES_REQUESTED** [review]
Could you also apply the StyleCI patch please?

**Comment by dunglas** [comment]
Thanks!

**Comment by darthf1** [comment]
Would it be possible to push a new release with this change? :)
